In [2]:
import pandas as pd
immigration = pd.read_csv("immigration1.csv")
immigration

,stname,name,fips,r1ttt0,r1ttt5,r1ttt10,r1ttt15,r1ttt20,r1ttt25,r1ttt30,...,e1ttt30,e1ttt35,e1ttt40,e1ttt45,e1ttt50,e1ttt55,e1ttt60,e1ttt65,e1ttt70,e1ttt75
0,Alabama,State Total,1000,0.63,3.14,1.71,6.25,6.20,0.12,-2.37,...,328576.19,308669.62,292749.06,299049.62,296611.12,322634.34,309316.81,264843.72,218222.09,151073.69
1,Alabama,Autauga County,1001,4.85,17.91,10.35,-2.57,-21.92,-6.69,25.64,...,3001.48,3105.82,3292.68,4038.35,3939.11,4085.46,3483.00,2628.37,2183.59,1620.94
2,Alabama,Baldwin County,1003,5.34,23.38,27.22,19.38,-1.89,10.39,41.56,...,9202.71,10099.24,10544.55,11246.33,11495.96,12612.46,12158.07,10783.76,9674.46,7689.06
3,Alabama,Barbour County,1005,-2.33,-4.88,-10.16,-9.85,-4.21,4.21,-7.29,...,1780.80,2047.48,1811.56,1791.88,1740.89,2003.35,1719.75,1536.10,1445.48,943.48
4,Alabama,Bibb County,1007,-4.47,-4.68,-12.58,-12.82,-6.61,11.23,10.56,...,1442.59,1609.06,1633.01,1719.70,1546.77,1675.91,1412.47,1136.45,1023.28,643.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3185,Wyoming,Sweetwater County,56037,-5.55,-7.07,-10.10,-11.98,-18.41,-8.53,-1.02,...,3034.82,3631.52,3312.80,2724.27,2436.12,2870.24,3202.31,2723.26,1797.71,997.16
3186,Wyoming,Teton County,56039,-7.96,-11.59,-4.88,-5.67,12.87,99.58,43.59,...,1355.28,2277.10,1960.90,1735.27,1537.30,1490.07,1535.49,1449.62,1148.10,760.06
3187,Wyoming,Uinta County,56041,-3.14,2.91,-5.01,-14.41,-39.14,-25.76,13.91,...,1049.11,1465.26,1383.11,1366.37,1158.10,1367.07,1615.53,1353.29,854.44,533.69
3188,Wyoming,Washakie County,56043,-9.36,-12.87,-13.65,-10.89,-40.69,-35.46,23.19,...,324.70,471.74,494.95,426.49,470.48,563.92,600.18,568.73,461.20,380.78
3189,Wyoming,Weston County,56045,-4.03,-1.79,-10.03,-18.59,-23.17,-6.91,3.04,...,389.17,432.63,444.95,392.99,417.28,531.85,569.72,544.61,391.79,241.26

In [3]:
df = immigration[immigration["name"] != "State Total"]
df

,stname,name,fips,r1ttt0,r1ttt5,r1ttt10,r1ttt15,r1ttt20,r1ttt25,r1ttt30,...,e1ttt30,e1ttt35,e1ttt40,e1ttt45,e1ttt50,e1ttt55,e1ttt60,e1ttt65,e1ttt70,e1ttt75
1,Alabama,Autauga County,1001,4.85,17.91,10.35,-2.57,-21.92,-6.69,25.64,...,3001.48,3105.82,3292.68,4038.35,3939.11,4085.46,3483.00,2628.37,2183.59,1620.94
2,Alabama,Baldwin County,1003,5.34,23.38,27.22,19.38,-1.89,10.39,41.56,...,9202.71,10099.24,10544.55,11246.33,11495.96,12612.46,12158.07,10783.76,9674.46,7689.06
3,Alabama,Barbour County,1005,-2.33,-4.88,-10.16,-9.85,-4.21,4.21,-7.29,...,1780.80,2047.48,1811.56,1791.88,1740.89,2003.35,1719.75,1536.10,1445.48,943.48
4,Alabama,Bibb County,1007,-4.47,-4.68,-12.58,-12.82,-6.61,11.23,10.56,...,1442.59,1609.06,1633.01,1719.70,1546.77,1675.91,1412.47,1136.45,1023.28,643.26
5,Alabama,Blount County,1009,3.22,6.22,6.10,-2.68,-18.79,-9.07,14.68,...,3011.78,3379.66,3374.11,3741.86,3829.15,3884.37,3472.96,3117.66,2815.41,2099.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3185,Wyoming,Sweetwater County,56037,-5.55,-7.07,-10.10,-11.98,-18.41,-8.53,-1.02,...,3034.82,3631.52,3312.80,2724.27,2436.12,2870.24,3202.31,2723.26,1797.71,997.16
3186,Wyoming,Teton County,56039,-7.96,-11.59,-4.88,-5.67,12.87,99.58,43.59,...,1355.28,2277.10,1960.90,1735.27,1537.30,1490.07,1535.49,1449.62,1148.10,760.06
3187,Wyoming,Uinta County,56041,-3.14,2.91,-5.01,-14.41,-39.14,-25.76,13.91,...,1049.11,1465.26,1383.11,1366.37,1158.10,1367.07,1615.53,1353.29,854.44,533.69
3188,Wyoming,Washakie County,56043,-9.36,-12.87,-13.65,-10.89,-40.69,-35.46,23.19,...,324.70,471.74,494.95,426.49,470.48,563.92,600.18,568.73,461.20,380.78
3189,Wyoming,Weston County,56045,-4.03,-1.79,-10.03,-18.59,-23.17,-6.91,3.04,...,389.17,432.63,444.95,392.99,417.28,531.85,569.72,544.61,391.79,241.26

In [4]:
df['name'] = df['name'].str.replace(r"\s*County$", "", regex=True)
df = df.sort_values(by='name').reset_index(drop=True)
df

/var/folders/26/l89mqgp17zj82yvlmd3z3r200000ks/T/ipykernel_39513/1474136259.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['name'] = df['name'].str.replace(r"\s*County$", "", regex=True)

,stname,name,fips,r1ttt0,r1ttt5,r1ttt10,r1ttt15,r1ttt20,r1ttt25,r1ttt30,...,e1ttt30,e1ttt35,e1ttt40,e1ttt45,e1ttt50,e1ttt55,e1ttt60,e1ttt65,e1ttt70,e1ttt75
0,South Carolina,Abbeville,45001,-1.34,-1.19,-4.58,3.01,-2.78,-27.26,-20.06,...,1522.47,1192.19,1260.20,1467.03,1519.27,1676.19,1677.83,1658.30,1449.66,1017.17
1,Louisiana,Acadia Parish,22001,-10.85,-8.98,-11.27,-14.32,-26.20,-18.43,-4.28,...,3882.27,3977.13,3643.08,3342.77,3734.04,4213.07,3947.49,3218.44,2387.02,1693.38
2,Virginia,Accomack,51001,-0.65,-7.37,-0.13,-6.86,-15.57,-8.94,4.90,...,1698.73,1822.83,1689.77,1716.09,1898.39,2224.36,2377.45,2248.28,1901.85,1460.91
3,Idaho,Ada,16001,6.15,20.24,19.00,14.00,5.78,31.77,38.96,...,25141.54,28883.84,28259.64,27873.54,26939.88,27139.13,25014.66,21216.28,16807.59,10556.62
4,Missouri,Adair,29001,-7.09,-9.33,-14.97,109.99,281.10,-46.93,-74.65,...,4583.27,1440.81,1053.37,1135.35,1260.99,1396.22,1340.89,1209.80,1000.28,737.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3134,Colorado,Yuma,8125,3.14,7.81,-1.37,-10.00,-22.47,-16.56,21.56,...,494.39,636.27,574.03,605.28,591.17,643.07,671.82,583.75,483.44,367.46
3135,Arizona,Yuma,4027,-5.29,-8.58,-10.35,-2.15,4.37,-6.75,-9.08,...,14702.24,13109.58,11333.11,11220.78,11358.16,11088.51,10215.97,8501.38,7743.74,7279.03
3136,Texas,Zapata,48505,-4.06,-11.08,-11.41,-9.74,-17.01,-28.73,-26.90,...,1080.67,989.32,897.43,843.57,775.95,744.72,600.31,558.47,505.20,379.94
3137,Texas,Zavala,48507,-17.89,-19.47,-24.64,-18.70,-22.71,-34.40,-35.64,...,908.97,765.87,643.12,643.48,637.18,591.58,609.22,568.69,483.07,331.17
3138,South Dakota,Ziebach,46137,-2.89,-25.15,-37.97,-18.57,-19.50,-27.99,-46.50,...,185.06,208.50,160.72,146.96,132.21,174.01,143.55,103.35,79.11,40.95

In [5]:
df.to_csv('immigration_cleaned.csv', index=False)