In [52]:
import pandas as pd

pd.set_option('display.max_rows', 200)

In [53]:
wiki = pd.read_csv("wikicounty.csv")
wiki

,Unnamed: 0,Sort [1],State,FIPS,County [2],County Seat(s) [3],Population (2010),Land Area km²,Land Area mi²,Water Area km²,Water Area mi²,Total Area km²,Total Area mi²,Latitude,Longitude
0,0,1,AL,1001,Autauga,Prattville,54571,1539.582,594.436,25.776,9.952,1565.358,604.388,+32.536382°,–86.644490°
1,1,2,AL,1003,Baldwin,Bay Minette,182265,4117.522,1589.784,1133.190,437.527,5250.712,2027.311,+30.659218°,–87.746067°
2,2,3,AL,1005,Barbour,Clayton,27457,2291.819,884.876,50.865,19.639,2342.684,904.515,+31.870670°,–85.405456°
3,3,4,AL,1007,Bibb,Centreville,22915,1612.481,622.582,9.289,3.587,1621.770,626.169,+33.015893°,–87.127148°
4,4,5,AL,1009,Blount,Oneonta,57322,1669.962,644.776,15.157,5.852,1685.119,650.628,+33.977448°,–86.567246°
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,3138,3139,WY,56037,Sweetwater,Green River,43806,27004.897,10426.649,166.887,64.436,27171.784,10491.085,+41.660339°,–108.875676°
3139,3139,3140,WY,56039,Teton,Jackson,21294,10347.984,3995.379,572.266,220.953,10920.250,4216.332,+44.049321°,–110.588102°
3140,3140,3141,WY,56041,Uinta,Evanston,21118,5390.450,2081.264,16.342,6.310,5406.791,2087.574,+41.284726°,–110.558947°
3141,3141,3142,WY,56043,Washakie,Worland,8533,5797.815,2238.549,10.762,4.155,5808.577,2242.704,+43.878831°,–107.669052°
3142,3142,3143,WY,56045,Weston,Newcastle,7208,6211.021,2398.089,5.002,1.931,6216.023,2400.020,+43.846213°,–104.570020°

In [31]:
wiki = wiki.sort_values(by = "County [2]")
wiki = wiki.reset_index(drop = True)
wiki

,Unnamed: 0,Sort [1],State,FIPS,County [2],County Seat(s) [3],Population (2010),Land Area km²,Land Area mi²,Water Area km²,Water Area mi²,Total Area km²,Total Area mi²,Latitude,Longitude
0,2316,2317,SC,45001,Abbeville,Abbeville,25417,1270.348,490.484,53.116,20.508,1323.464,510.992,+34.213809°,–82.460460°
1,1113,1114,LA,22001,Acadia,Crowley,61773,1696.751,655.119,6.049,2.335,1702.799,657.454,+30.291497°,–92.411037°
2,2820,2821,VA,51001,Accomack,Accomac,33164,1164.189,449.496,2228.794,860.542,3392.983,1310.038,+37.765944°,–75.757807°
3,551,552,ID,16001,Ada,Boise,392365,2726.158,1052.576,20.425,7.886,2746.583,1060.462,+43.447861°,–116.244456°
4,993,994,KY,21001,Adair,Columbia,18656,1049.677,405.283,18.432,7.117,1068.109,412.400,+37.105541°,–85.281401°
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,110,111,AZ,4027,Yuma,Yuma,195751,14281.174,5513.992,13.254,5.117,14294.428,5519.109,+32.773942°,–113.910905°
3139,307,308,CO,8125,Yuma,Wray,10043,6123.780,2364.405,11.135,4.299,6134.915,2368.704,+40.000631°,–102.422649°
3140,2775,2776,TX,48505,Zapata,Zapata,14018,2585.876,998.412,154.371,59.603,2740.247,1058.015,+26.996981°,–99.182603°
3141,2776,2777,TX,48507,Zavala,Crystal City,11677,3360.267,1297.406,11.210,4.328,3371.477,1301.734,+28.864652°,–99.759830°
3142,2427,2428,SD,46137,Ziebach,Dupree,2801,5079.670,1961.272,24.212,9.348,5103.883,1970.620,+44.981666°,–101.669225°

In [54]:
data = pd.read_csv("original_dataset.csv")
data

/var/folders/26/l89mqgp17zj82yvlmd3z3r200000ks/T/ipykernel_49102/1021443775.py:1: DtypeWarning: Columns (249,250,257,258,259,266,267,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,309,315,316,317,319,321,325,326,327,338,339,345,346,347,348,349,350,351,354,355,356,357,372,373,374,377,385,386,387,388,389,390,391,393,394) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("original_dataset.csv")

,statecounty_x,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2016,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2017,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2018,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2019,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2020,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2021,Percent_Of_Days_With_Level_Of_PM2.5_Exceeding_The_Standard_EPA2016,Percent_Of_Days_With_Level_Of_PM2.5_Exceeding_The_Standard_EPA2017,Percent_Of_Days_With_Level_Of_PM2.5_Exceeding_The_Standard_EPA2018,...,Number_of_FDPIR_Available_USDA_2015,Number_of_Food_Banks_Available_USDA_2016,Number_of_Farmers_Market_Accept_SNAP_USDA_2018,Percent_of_Farmers_Market_Accept_SNAP_USDA_2018,Number_of_Farmers_Market_Accept_WIC_USDA_2018,Percent_of_Farmers_Market_Accept_WIC_USDA_2018,Number_of_Farmers_Market_Accept_WIC_Cash_USDA_2018,Number_of_Farmers_Market_Accept_SFMNP_USDA_2018,Percent_of_Farmers_Market_Accept_SFMNP_USDA_2018,Number_of_Recreation_Fitness_Facilities_Per1000_Residents_USDA_2016
0,01Autauga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,6.0
1,01Baldwin,7.2,7.4,7.1,7.5,7.9,7.3,0.0%,0.0%,0.0%,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,4.0,100.0,21.0
2,01Barbour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,2.0,50.000000,0.0,0.0,0.0,2.0,50.0,0.0
3,01Bibb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.0
4,01Blount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,1.0,100.0,0.0,1.0,100.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,56Sweetwater,5.0,5.6,5.4,4.4,3.6,NaN,0.0%,0.0%,0.0%,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,6.0
3139,56Teton,4.4,4.8,5.1,3.6,4.8,5.1,0.0%,0.3%,0.3%,...,0.0,0.0,1.0,33.333332,0.0,0.0,0.0,0.0,0.0,13.0
3140,56Uinta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,2.0
3141,56Washakie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.0
3142,56Weston,2.9,NaN,NaN,NaN,NaN,NaN,0.0%,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [62]:

data['statecounty_x'] = data['statecounty_x'].str.replace(r'\d+', '', regex=True)
data['statecounty_x'] = data['statecounty_x'].str.split().str[0]
data['statecounty_x'] = data['statecounty_x'].str.split().str[0].str.lower()
data = data.sort_values(by = "statecounty_x")
data

,statecounty_x,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2016,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2017,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2018,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2019,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2020,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2021,Percent_Of_Days_With_Level_Of_PM2.5_Exceeding_The_Standard_EPA2016,Percent_Of_Days_With_Level_Of_PM2.5_Exceeding_The_Standard_EPA2017,Percent_Of_Days_With_Level_Of_PM2.5_Exceeding_The_Standard_EPA2018,...,Number_of_FDPIR_Available_USDA_2015,Number_of_Food_Banks_Available_USDA_2016,Number_of_Farmers_Market_Accept_SNAP_USDA_2018,Percent_of_Farmers_Market_Accept_SNAP_USDA_2018,Number_of_Farmers_Market_Accept_WIC_USDA_2018,Percent_of_Farmers_Market_Accept_WIC_USDA_2018,Number_of_Farmers_Market_Accept_WIC_Cash_USDA_2018,Number_of_Farmers_Market_Accept_SFMNP_USDA_2018,Percent_of_Farmers_Market_Accept_SFMNP_USDA_2018,Number_of_Recreation_Fitness_Facilities_Per1000_Residents_USDA_2016
2317,abbeville,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,1.0,50.000000,0.0
1114,acadia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,10.0
2821,accomack,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,33.333332,0.0,0.0,0.0,1.0,33.333332,2.0
552,ada,6.3,9.2,7.9,5.3,7.7,9.3,0.0%,5.0%,0.8%,...,0.0,1.0,3.0,42.857143,0.0,0.0,0.0,0.0,0.000000,51.0
790,adair,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,yuma,8.3,8.5,8.7,7.9,9.1,9.3,0.9%,0.5%,0.0%,...,0.0,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,12.0
308,yuma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
2776,zapata,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
2777,zavala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
2428,ziebach,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,1.0

In [44]:
wiki = wiki.sort_values(by = "County [2]")
wiki["County [2]"] = wiki["County [2]"].str.lower()
wiki

,Unnamed: 0,Sort [1],State,FIPS,County [2],County Seat(s) [3],Population (2010),Land Area km²,Land Area mi²,Water Area km²,Water Area mi²,Total Area km²,Total Area mi²,Latitude,Longitude
0,2316,2317,SC,45001,abbeville,Abbeville,25417,1270.348,490.484,53.116,20.508,1323.464,510.992,+34.213809°,–82.460460°
1,1113,1114,LA,22001,acadia,Crowley,61773,1696.751,655.119,6.049,2.335,1702.799,657.454,+30.291497°,–92.411037°
2,2820,2821,VA,51001,accomack,Accomac,33164,1164.189,449.496,2228.794,860.542,3392.983,1310.038,+37.765944°,–75.757807°
3,551,552,ID,16001,ada,Boise,392365,2726.158,1052.576,20.425,7.886,2746.583,1060.462,+43.447861°,–116.244456°
4,993,994,KY,21001,adair,Columbia,18656,1049.677,405.283,18.432,7.117,1068.109,412.400,+37.105541°,–85.281401°
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,110,111,AZ,4027,yuma,Yuma,195751,14281.174,5513.992,13.254,5.117,14294.428,5519.109,+32.773942°,–113.910905°
3139,307,308,CO,8125,yuma,Wray,10043,6123.780,2364.405,11.135,4.299,6134.915,2368.704,+40.000631°,–102.422649°
3140,2775,2776,TX,48505,zapata,Zapata,14018,2585.876,998.412,154.371,59.603,2740.247,1058.015,+26.996981°,–99.182603°
3141,2776,2777,TX,48507,zavala,Crystal City,11677,3360.267,1297.406,11.210,4.328,3371.477,1301.734,+28.864652°,–99.759830°
3142,2427,2428,SD,46137,ziebach,Dupree,2801,5079.670,1961.272,24.212,9.348,5103.883,1970.620,+44.981666°,–101.669225°