In [114]:
import pandas as pd

pd.set_option('display.max_rows', 200)

In [115]:
wiki = pd.read_csv("wikicounty.csv")
wiki

,Unnamed: 0,Sort [1],State,FIPS,County [2],County Seat(s) [3],Population (2010),Land Area km²,Land Area mi²,Water Area km²,Water Area mi²,Total Area km²,Total Area mi²,Latitude,Longitude
0,0,1,AL,1001,Autauga,Prattville,54571,1539.582,594.436,25.776,9.952,1565.358,604.388,+32.536382°,–86.644490°
1,1,2,AL,1003,Baldwin,Bay Minette,182265,4117.522,1589.784,1133.190,437.527,5250.712,2027.311,+30.659218°,–87.746067°
2,2,3,AL,1005,Barbour,Clayton,27457,2291.819,884.876,50.865,19.639,2342.684,904.515,+31.870670°,–85.405456°
3,3,4,AL,1007,Bibb,Centreville,22915,1612.481,622.582,9.289,3.587,1621.770,626.169,+33.015893°,–87.127148°
4,4,5,AL,1009,Blount,Oneonta,57322,1669.962,644.776,15.157,5.852,1685.119,650.628,+33.977448°,–86.567246°
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,3138,3139,WY,56037,Sweetwater,Green River,43806,27004.897,10426.649,166.887,64.436,27171.784,10491.085,+41.660339°,–108.875676°
3139,3139,3140,WY,56039,Teton,Jackson,21294,10347.984,3995.379,572.266,220.953,10920.250,4216.332,+44.049321°,–110.588102°
3140,3140,3141,WY,56041,Uinta,Evanston,21118,5390.450,2081.264,16.342,6.310,5406.791,2087.574,+41.284726°,–110.558947°
3141,3141,3142,WY,56043,Washakie,Worland,8533,5797.815,2238.549,10.762,4.155,5808.577,2242.704,+43.878831°,–107.669052°
3142,3142,3143,WY,56045,Weston,Newcastle,7208,6211.021,2398.089,5.002,1.931,6216.023,2400.020,+43.846213°,–104.570020°

In [116]:
wiki = wiki.sort_values(by = "County [2]")
wiki = wiki.reset_index(drop = True)
wiki

,Unnamed: 0,Sort [1],State,FIPS,County [2],County Seat(s) [3],Population (2010),Land Area km²,Land Area mi²,Water Area km²,Water Area mi²,Total Area km²,Total Area mi²,Latitude,Longitude
0,2316,2317,SC,45001,Abbeville,Abbeville,25417,1270.348,490.484,53.116,20.508,1323.464,510.992,+34.213809°,–82.460460°
1,1113,1114,LA,22001,Acadia,Crowley,61773,1696.751,655.119,6.049,2.335,1702.799,657.454,+30.291497°,–92.411037°
2,2820,2821,VA,51001,Accomack,Accomac,33164,1164.189,449.496,2228.794,860.542,3392.983,1310.038,+37.765944°,–75.757807°
3,551,552,ID,16001,Ada,Boise,392365,2726.158,1052.576,20.425,7.886,2746.583,1060.462,+43.447861°,–116.244456°
4,993,994,KY,21001,Adair,Columbia,18656,1049.677,405.283,18.432,7.117,1068.109,412.400,+37.105541°,–85.281401°
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,110,111,AZ,4027,Yuma,Yuma,195751,14281.174,5513.992,13.254,5.117,14294.428,5519.109,+32.773942°,–113.910905°
3139,307,308,CO,8125,Yuma,Wray,10043,6123.780,2364.405,11.135,4.299,6134.915,2368.704,+40.000631°,–102.422649°
3140,2775,2776,TX,48505,Zapata,Zapata,14018,2585.876,998.412,154.371,59.603,2740.247,1058.015,+26.996981°,–99.182603°
3141,2776,2777,TX,48507,Zavala,Crystal City,11677,3360.267,1297.406,11.210,4.328,3371.477,1301.734,+28.864652°,–99.759830°
3142,2427,2428,SD,46137,Ziebach,Dupree,2801,5079.670,1961.272,24.212,9.348,5103.883,1970.620,+44.981666°,–101.669225°

In [117]:
data = pd.read_csv("original_dataset.csv")
data

/var/folders/5b/z7m8dzcs5td_8q7jrcf_9spm0000gn/T/ipykernel_1299/1021443775.py:1: DtypeWarning: Columns (249,250,257,258,259,266,267,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,309,315,316,317,319,321,325,326,327,338,339,345,346,347,348,349,350,351,354,355,356,357,372,373,374,377,385,386,387,388,389,390,391,393,394) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("original_dataset.csv")

,statecounty_x,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2016,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2017,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2018,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2019,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2020,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2021,Percent_Of_Days_With_Level_Of_PM2.5_Exceeding_The_Standard_EPA2016,Percent_Of_Days_With_Level_Of_PM2.5_Exceeding_The_Standard_EPA2017,Percent_Of_Days_With_Level_Of_PM2.5_Exceeding_The_Standard_EPA2018,...,Number_of_FDPIR_Available_USDA_2015,Number_of_Food_Banks_Available_USDA_2016,Number_of_Farmers_Market_Accept_SNAP_USDA_2018,Percent_of_Farmers_Market_Accept_SNAP_USDA_2018,Number_of_Farmers_Market_Accept_WIC_USDA_2018,Percent_of_Farmers_Market_Accept_WIC_USDA_2018,Number_of_Farmers_Market_Accept_WIC_Cash_USDA_2018,Number_of_Farmers_Market_Accept_SFMNP_USDA_2018,Percent_of_Farmers_Market_Accept_SFMNP_USDA_2018,Number_of_Recreation_Fitness_Facilities_Per1000_Residents_USDA_2016
0,01Autauga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,6.0
1,01Baldwin,7.2,7.4,7.1,7.5,7.9,7.3,0.0%,0.0%,0.0%,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,4.0,100.0,21.0
2,01Barbour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,2.0,50.000000,0.0,0.0,0.0,2.0,50.0,0.0
3,01Bibb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.0
4,01Blount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,1.0,100.0,0.0,1.0,100.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,56Sweetwater,5.0,5.6,5.4,4.4,3.6,NaN,0.0%,0.0%,0.0%,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,6.0
3139,56Teton,4.4,4.8,5.1,3.6,4.8,5.1,0.0%,0.3%,0.3%,...,0.0,0.0,1.0,33.333332,0.0,0.0,0.0,0.0,0.0,13.0
3140,56Uinta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,2.0
3141,56Washakie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.0
3142,56Weston,2.9,NaN,NaN,NaN,NaN,NaN,0.0%,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [118]:

# data['statecounty_x'] = data['statecounty_x'].str.replace(r'\d+', '', regex=True)
# data['statecounty_x'] = data['statecounty_x'].str.split().str[0]
data['statecounty_x'] = data['statecounty_x'].str.split().str[0].str.lower()
data = data.sort_values(by = "statecounty_x")
data

,statecounty_x,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2016,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2017,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2018,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2019,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2020,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2021,Percent_Of_Days_With_Level_Of_PM2.5_Exceeding_The_Standard_EPA2016,Percent_Of_Days_With_Level_Of_PM2.5_Exceeding_The_Standard_EPA2017,Percent_Of_Days_With_Level_Of_PM2.5_Exceeding_The_Standard_EPA2018,...,Number_of_FDPIR_Available_USDA_2015,Number_of_Food_Banks_Available_USDA_2016,Number_of_Farmers_Market_Accept_SNAP_USDA_2018,Percent_of_Farmers_Market_Accept_SNAP_USDA_2018,Number_of_Farmers_Market_Accept_WIC_USDA_2018,Percent_of_Farmers_Market_Accept_WIC_USDA_2018,Number_of_Farmers_Market_Accept_WIC_Cash_USDA_2018,Number_of_Farmers_Market_Accept_SFMNP_USDA_2018,Percent_of_Farmers_Market_Accept_SFMNP_USDA_2018,Number_of_Recreation_Fitness_Facilities_Per1000_Residents_USDA_2016
0,01autauga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,6.0
1,01baldwin,7.2,7.4,7.1,7.5,7.9,7.3,0.0%,0.0%,0.0%,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,4.0,100.0,21.0
2,01barbour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,2.0,50.000000,0.0,0.0,0.0,2.0,50.0,0.0
3,01bibb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.0
4,01blount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,1.0,100.0,0.0,1.0,100.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,56sweetwater,5.0,5.6,5.4,4.4,3.6,NaN,0.0%,0.0%,0.0%,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,6.0
3139,56teton,4.4,4.8,5.1,3.6,4.8,5.1,0.0%,0.3%,0.3%,...,0.0,0.0,1.0,33.333332,0.0,0.0,0.0,0.0,0.0,13.0
3140,56uinta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,2.0
3141,56washakie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.0
3142,56weston,2.9,NaN,NaN,NaN,NaN,NaN,0.0%,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [119]:
wiki = wiki.sort_values(by = "County [2]")
wiki["County [2]"] = wiki["County [2]"].str.lower()
len(wiki.columns)

15

In [120]:
wiki['fips_county'] = wiki['FIPS'].astype(str).str[:2] + wiki['County [2]']
wiki["fips_county"]
wiki = wiki.sort_values(by="fips_county")
wiki['fips_county'] = wiki['fips_county'].str.replace(r'\[\d+\]', '', regex=True)
wiki

,Unnamed: 0,Sort [1],State,FIPS,County [2],County Seat(s) [3],Population (2010),Land Area km²,Land Area mi²,Water Area km²,Water Area mi²,Total Area km²,Total Area mi²,Latitude,Longitude,fips_county
110,0,1,AL,1001,autauga,Prattville,54571,1539.582,594.436,25.776,9.952,1565.358,604.388,+32.536382°,–86.644490°,10autauga
120,1,2,AL,1003,baldwin,Bay Minette,182265,4117.522,1589.784,1133.190,437.527,5250.712,2027.311,+30.659218°,–87.746067°,10baldwin
131,2,3,AL,1005,barbour,Clayton,27457,2291.819,884.876,50.865,19.639,2342.684,904.515,+31.870670°,–85.405456°,10barbour
203,3,4,AL,1007,bibb,Centreville,22915,1612.481,622.582,9.289,3.587,1621.770,626.169,+33.015893°,–87.127148°,10bibb
222,4,5,AL,1009,blount,Oneonta,57322,1669.962,644.776,15.157,5.852,1685.119,650.628,+33.977448°,–86.567246°,10blount
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1914,311,312,CT,9007,middlesex [6],Middletown [6],165676,956.486,369.301,180.684,69.762,1137.170,439.063,+41.434525°,–72.524227°,90middlesex
2059,312,313,CT,9009,new haven [6],New Haven [6],862477,1565.663,604.506,667.053,257.551,2232.716,862.057,+41.349717°,–72.900204°,90new haven
2061,313,314,CT,9011,new london [6],New London [6],274055,1722.026,664.878,276.666,106.821,1998.692,771.699,+41.478630°,–72.103452°,90new london
2805,314,315,CT,9013,tolland [6],Rockville [6],152691,1062.448,410.214,17.698,6.833,1080.147,417.047,+41.858076°,–72.340977°,90tolland
3074,315,316,CT,9015,windham [6],Willimantic [6],118428,1328.430,512.910,22.092,8.530,1350.523,521.440,+41.824999°,–71.990702°,90windham

In [121]:
immi = pd.read_csv("immigration_cleaned.csv")

immi['fips_county'] = immi['fips'].astype(str).str[:2] + immi['name']
immi = immi.sort_values(by="fips_county")
immi.columns

datadict = pd.read_csv("../data_about_the_immigration/NME_1020_datadict.csv")

# Adjust the mapping to retain unmatched columns with their original names
mapped_varlabs = {col: datadict[datadict["name"] == col]["varlab"].values[0] 
                  if col in datadict["name"].values else col for col in immi.columns}

# Rename the columns in the immi dataframe
immi.rename(columns=mapped_varlabs, inplace=True)
immi

,stname,name,fips,"Net Migration Rate 2010s, total, ages 00-04","Net Migration Rate 2010s, total, ages 05-09","Net Migration Rate 2010s, total, ages 10-14","Net Migration Rate 2010s, total, ages 15-19","Net Migration Rate 2010s, total, ages 20-24","Net Migration Rate 2010s, total, ages 25-29","Net Migration Rate 2010s, total, ages 30-34",...,"Expected Population 2020, total, ages 35-39","Expected Population 2020, total, ages 40-44","Expected Population 2020, total, ages 45-49","Expected Population 2020, total, ages 50-54","Expected Population 2020, total, ages 55-59","Expected Population 2020, total, ages 60-64","Expected Population 2020, total, ages 65-69","Expected Population 2020, total, ages 70-74","Expected Population 2020, total, ages 75-79",fips_county
110,Alabama,autauga,1001,4.85,17.91,10.35,-2.57,-21.92,-6.69,25.64,...,3105.82,3292.68,4038.35,3939.11,4085.46,3483.00,2628.37,2183.59,1620.94,10autauga
120,Alabama,baldwin,1003,5.34,23.38,27.22,19.38,-1.89,10.39,41.56,...,10099.24,10544.55,11246.33,11495.96,12612.46,12158.07,10783.76,9674.46,7689.06,10baldwin
132,Alabama,barbour,1005,-2.33,-4.88,-10.16,-9.85,-4.21,4.21,-7.29,...,2047.48,1811.56,1791.88,1740.89,2003.35,1719.75,1536.10,1445.48,943.48,10barbour
201,Alabama,bibb,1007,-4.47,-4.68,-12.58,-12.82,-6.61,11.23,10.56,...,1609.06,1633.01,1719.70,1546.77,1675.91,1412.47,1136.45,1023.28,643.26,10bibb
222,Alabama,blount,1009,3.22,6.22,6.10,-2.68,-18.79,-9.07,14.68,...,3379.66,3374.11,3741.86,3829.15,3884.37,3472.96,3117.66,2815.41,2099.01,10blount
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1914,Connecticut,middlesex,9007,4.70,4.56,0.06,3.48,-6.41,-10.36,12.06,...,8500.91,8534.79,9952.20,12438.08,13752.77,13294.08,11453.57,9479.66,6428.20,90middlesex
2063,Connecticut,new,9011,2.35,3.29,-0.70,3.27,10.12,-1.25,-9.11,...,16859.87,15519.02,16238.65,19196.51,21576.59,20702.12,17180.94,13643.24,9639.38,90new
2062,Connecticut,new,9009,3.64,4.22,2.42,11.77,2.72,-4.74,-2.14,...,55812.68,51529.34,51963.26,59520.27,63886.36,61509.24,50758.59,41754.77,28427.89,90new
2804,Connecticut,tolland,9013,6.56,17.31,8.71,63.53,95.71,-36.20,-49.65,...,7913.48,7514.98,8719.99,10620.00,12233.05,11867.60,9428.39,7281.97,5105.77,90tolland
3070,Connecticut,windham,9015,4.37,7.93,1.85,10.39,-3.10,-20.13,-8.37,...,6817.88,6827.40,7562.49,8178.77,9314.26,8917.18,7241.25,5591.24,3695.24,90windham

In [122]:
print("Unique fips_county in immi:", immi['fips_county'].nunique())
print("Unique fips_county in wiki:", wiki['fips_county'].nunique())
immi['fips_county'] = immi['fips_county'].str.lower().str.strip()
wiki['fips_county'] = wiki['fips_county'].str.lower().str.strip()

Unique fips_county in immi: 3086
Unique fips_county in wiki: 3139

In [123]:
merged_data = pd.merge(immi, wiki, on='fips_county', how='inner')
print("Number of rows after inner merge:", merged_data.shape)
print(merged_data.sort_values("name"))

Number of rows after inner merge: (2956, 67)
              stname       name   fips  \
1988  South Carolina  abbeville  45001
845        Louisiana     acadia  22001
2516        Virginia   accomack  51001
290            Idaho        ada  16001
721         Kentucky      adair  21001
...              ...        ...    ...
2949        Colorado       yuma   8125
1880         Arizona       yuma   4027
2425           Texas     zapata  48505
2426           Texas     zavala  48507
2095    South Dakota    ziebach  46137

      Net Migration Rate 2010s, total, ages 00-04  \
1988                                        -1.34
845                                        -10.85
2516                                        -0.65
290                                          6.15
721                                         -5.23
...                                           ...
2949                                         3.14
1880                                        -5.29
2425                                        -4.06
2426                                       -17.89
2095                                        -2.89

      Net Migration Rate 2010s, total, ages 05-09  \
1988                                        -1.19
845                                         -8.98
2516                                        -7.37
290                                         20.24
721                                         -1.42
...                                           ...
2949                                         7.81
1880                                        -8.58
2425                                       -11.08
2426                                       -19.47
2095                                       -25.15

      Net Migration Rate 2010s, total, ages 10-14  \
1988                                        -4.58
845                                        -11.27
2516                                        -0.13
290                                         19.00
721                                        -10.74
...                                           ...
2949                                        -1.37
1880                                       -10.35
2425                                       -11.41
2426                                       -24.64
2095                                       -37.97

      Net Migration Rate 2010s, total, ages 15-19  \
1988                                         3.01
845                                        -14.32
2516                                        -6.86
290                                         14.00
721                                         33.89
...                                           ...
2949                                       -10.00
1880                                        -2.15
2425                                        -9.74
2426                                       -18.70
2095                                       -18.57

      Net Migration Rate 2010s, total, ages 20-24  \
1988                                        -2.78
845                                        -26.20
2516                                       -15.57
290                                          5.78
721                                         24.93
...                                           ...
2949                                       -22.47
1880                                         4.37
2425                                       -17.01
2426                                       -22.71
2095                                       -19.50

      Net Migration Rate 2010s, total, ages 25-29  \
1988                                       -27.26
845                                        -18.43
2516                                        -8.94
290                                         31.77
721                                        -28.49
...                                           ...
2949                                       -16.56
1880                                        -6.75
2425                                       -28.73
2426                                       -34.40
2095                                       -27.99

      Net Migration Rate 2010s, total, ages 30-34  ...  County Seat(s) [3]  \
1988                                       -20.06  ...           Abbeville
845                                         -4.28  ...             Crowley
2516                                         4.90  ...             Accomac
290                                         38.96  ...               Boise
721                                        -23.44  ...            Columbia
...                                           ...  ...                 ...
2949                                        21.56  ...                Wray
1880                                        -9.08  ...                Yuma
2425                                       -26.90  ...              Zapata
2426                                       -35.64  ...        Crystal City
2095                                       -46.50  ...              Dupree

      Population (2010)  Land Area km²  Land Area mi²  Water Area km²  \
1988              25417       1270.348        490.484          53.116
845               61773       1696.751        655.119           6.049
2516              33164       1164.189        449.496        2228.794
290              392365       2726.158       1052.576          20.425
721               18656       1049.677        405.283          18.432
...                 ...            ...            ...             ...
2949              10043       6123.780       2364.405          11.135
1880             195751      14281.174       5513.992          13.254
2425              14018       2585.876        998.412         154.371
2426              11677       3360.267       1297.406          11.210
2095               2801       5079.670       1961.272          24.212

      Water Area mi²  Total Area km²  Total Area mi²     Latitude  \
1988          20.508        1323.464         510.992  +34.213809°
845            2.335        1702.799         657.454  +30.291497°
2516         860.542        3392.983        1310.038  +37.765944°
290            7.886        2746.583        1060.462  +43.447861°
721            7.117        1068.109         412.400  +37.105541°
...              ...             ...             ...          ...
2949           4.299        6134.915        2368.704  +40.000631°
1880           5.117       14294.428        5519.109  +32.773942°
2425          59.603        2740.247        1058.015  +26.996981°
2426           4.328        3371.477        1301.734  +28.864652°
2095           9.348        5103.883        1970.620  +44.981666°

         Longitude
1988   –82.460460°
845    –92.411037°
2516   –75.757807°
290   –116.244456°
721    –85.281401°
...            ...
2949  –102.422649°
1880  –113.910905°
2425   –99.182603°
2426   –99.759830°
2095  –101.669225°

[2956 rows x 67 columns]

In [124]:

not_in_wiki = immi[~immi['fips_county'].isin(wiki['fips_county'])]
print("Entries in immi not in wiki:")
print(not_in_wiki['fips_county'].unique())

not_in_immi = wiki[~wiki['fips_county'].isin(immi['fips_county'])]
print("Entries in wiki not in immi:")
print(not_in_immi['fips_county'].unique())

Entries in immi not in wiki:
['10new' '11district' '11st.' '12indian' '12palm' '12santa' '12st.'
 '13ben' '13jeff' '15hawaii' '15kauai' '16bear' '16nez' '16twin' '17de'
 '17jo' '17lasalle' '17rock' '17st.' '18st.' '19black' '19buena' '19cerro'
 '19des' '19palo' '19van' '20aleutians' '20bristol' '20fairbanks'
 '21kenai' '21ketchikan' '21kodiak' '21kusilvak' '21lake' '21north'
 '21northwest' '22de' '22east' '22lasalle' '22pointe' '22red'
 '22southeast' '22st.' '22west' '24anne' '24prince' '24queen' '24st.'
 '26grand' '26presque' '26st.' '26van' '27big' '27blue' '27crow' '27lac'
 '27le' '27mille' '27otter' '27red' '27st.' '27yellow' '28pearl' '29cape'
 '29chugach-copper' '29new' '29petersburg-prince'
 '29skagway-hoonah-angoon' '29st.' '29ste.' '30big' '30deer' '30golden'
 '30judith' '30lewis' '30powder' '30silver' '30sweet' '31box' '31keya'
 '31red' '31scotts' '32carson' '32white' '34cape' '35de' '35do??a' '35los'
 '35rio' '35san' '35santa' '36new' '36st.' '37new' '38golden' '38grand'
 '39van' '40la' '40le' '40roger' '40santa' '41hood' '46bon' '46charles'
 '46fall' '46oglala' '47van' '48deaf' '48el' '48fort' '48jeff' '48jim'
 '48la' '48live' '48palo' '48red' '48san' '48tom' '48val' '48van' '49box'
 '49salt' '49san' '50grand' '50hot' '50little' '51buena' '51charles'
 '51colonial' '51falls' '51isle' '51james' '51king' '51new' '51newport'
 '51prince' '51st.' '51van' '51virginia' '53grays' '53pend' '53san'
 '53walla' '55eau' '55fond' '55la' '55st.' '56big' '56hot' '60contra'
 '60del' '60el' '60los' '60san' '60santa' '80clear' '80el' '80kit' '80la'
 '80las' '81rio' '81san' '90new']
Entries in wiki not in immi:
['10new castle' '11district of columbia' '11st. clair' '12indian river'
 '12palm beach' '12santa rosa' '12st. johns' '12st. lucie' '13ben hill'
 '13jeff davis' '15hawaiʻi' '15kauaʻi' '16bear lake' '16nez perce'
 '16twin falls' '17de witt' '17jo daviess' '17la salle' '17rock island'
 '17st. clair' '18st. joseph' '19black hawk' '19buena vista'
 '19cerro gordo' '19des moines' '19palo alto' '19van buren'
 '20aleutians east' '20aleutians west' '20bristol bay'
 '20fairbanks north star' '21hoonah-angoon' '21kenai peninsula'
 '21ketchikan gateway' '21kodiak island' '21lake and peninsula'
 '21north slope' '21northwest arctic' '21petersburg'
 '21prince of wales-hyder' '22de soto' '22east baton rouge'
 '22east carroll' '22east feliciana' '22jefferson davis' '22la salle'
 '22pointe coupee' '22red river' '22skagway' '22southeast fairbanks'
 '22st. bernard' '22st. charles' '22st. helena' '22st. james'
 '22st. john the baptist' '22st. landry' '22st. martin' '22st. mary'
 '22st. tammany' '22valdez-cordova' '22wade hampton' '22west baton rouge'
 '22west carroll' '22west feliciana' '22wrangell' '24anne arundel'
 "24prince george's" "24queen anne's" "24st. mary's" '26grand traverse'
 '26presque isle' '26st. clair' '26st. joseph' '26van buren' '27big stone'
 '27blue earth' '27crow wing' '27lac qui parle' '27lake of the woods'
 '27le sueur' '27mille lacs' '27otter tail' '27red lake' '27st. louis'
 '27yellow medicine' '28jefferson davis' '28pearl river'
 '29cape girardeau' '29new madrid' '29st. charles' '29st. clair'
 '29st. francois' '29st. louis' '29ste. genevieve' '30big horn'
 '30deer lodge' '30golden valley' '30judith basin' '30lewis and clark'
 '30powder river' '30silver bow' '30sweet grass' '31box butte'
 '31keya paha' '31red willow' '31scotts bluff' '32carson city'
 '32white pine' '34cape may' '35de baca' '35dona ana' '35los alamos'
 '35rio arriba' '35san juan' '35san miguel' '35santa fe' '36new york'
 '36st. lawrence' '37new hanover' '38golden valley' '38grand forks'
 '39van wert' '40la paz' '40le flore' '40roger mills' '40santa cruz'
 '41hood river' '46bon homme' '46charles mix' '46fall river'
 '46oglala lakota' '47van buren' '48deaf smith' '48el paso' '48fort bend'
 '48jeff davis' '48jim hogg' '48jim wells' '48la salle' '48live oak'
 '48palo pinto' '48red river' '48san augustine' '48san jacinto'
 '48san patricio' '48san saba' '48tom green' '48val verde' '48van zandt'
 '49box elder' '49salt lake' '49san juan' '50grand isle' '50hot spring'
 '50little river' '51buena vista' '51charles city' '51colonial heights'
 '51falls church' '51isle of wight' '51james city' '51king and queen'
 '51king george' '51king william' '51manassas park' '51new kent'
 '51newport news' '51prince edward' '51prince george' '51prince william'
 '51st. francis' '51van buren' '51virginia beach' '53grays harbor'
 '53pend oreille' '53san juan' '53walla walla' '55eau claire'
 '55fond du lac' '55green lake' '55la crosse' '55st. croix' '56big horn'
 '56hot springs' '60contra costa' '60del norte' '60el dorado'
 '60los angeles' '60san benito' '60san bernardino' '60san diego'
 '60san francisco' '60san joaquin' '60san luis obispo' '60san mateo'
 '60santa barbara' '60santa clara' '60santa cruz' '80clear creek'
 '80el paso' '80kit carson' '80la plata' '80las animas' '81rio blanco'
 '81rio grande' '81san juan' '81san miguel' '90new haven' '90new london']

In [125]:
for i in range(min(len(not_in_immi), len(not_in_wiki))):
    print(not_in_wiki.iloc[i]['fips_county'], not_in_immi.iloc[i]['fips_county'])

10new 10new castle
11district 11district of columbia
11st. 11st. clair
12indian 12indian river
12palm 12palm beach
12santa 12santa rosa
12st. 12st. johns
12st. 12st. lucie
13ben 13ben hill
13jeff 13jeff davis
15hawaii 15hawaiʻi
15kauai 15kauaʻi
16bear 16bear lake
16nez 16nez perce
16twin 16twin falls
17de 17de witt
17jo 17jo daviess
17lasalle 17la salle
17rock 17rock island
17st. 17st. clair
18st. 18st. joseph
19black 19black hawk
19buena 19buena vista
19cerro 19cerro gordo
19des 19des moines
19palo 19palo alto
19van 19van buren
20aleutians 20aleutians east
20aleutians 20aleutians west
20bristol 20bristol bay
20fairbanks 20fairbanks north star
21kenai 21hoonah-angoon
21ketchikan 21kenai peninsula
21kodiak 21ketchikan gateway
21kusilvak 21kodiak island
21lake 21lake and peninsula
21north 21north slope
21northwest 21northwest arctic
22de 21petersburg
22east 21prince of wales-hyder
22east 22de soto
22east 22east baton rouge
22lasalle 22east carroll
22pointe 22east feliciana
22red 22jefferson davis
22southeast 22la salle
22st. 22pointe coupee
22st. 22red river
22st. 22skagway
22st. 22southeast fairbanks
22st. 22st. bernard
22st. 22st. charles
22st. 22st. helena
22st. 22st. james
22st. 22st. john the baptist
22west 22st. landry
22west 22st. martin
22west 22st. mary
24anne 22st. tammany
24prince 22valdez-cordova
24queen 22wade hampton
24st. 22west baton rouge
26grand 22west carroll
26presque 22west feliciana
26st. 22wrangell
26st. 24anne arundel
26van 24prince george's
27big 24queen anne's
27blue 24st. mary's
27crow 26grand traverse
27lac 26presque isle
27le 26st. clair
27mille 26st. joseph
27otter 26van buren
27red 27big stone
27st. 27blue earth
27yellow 27crow wing
28pearl 27lac qui parle
29cape 27lake of the woods
29chugach-copper 27le sueur
29new 27mille lacs
29petersburg-prince 27otter tail
29skagway-hoonah-angoon 27red lake
29st. 27st. louis
29st. 27yellow medicine
29st. 28jefferson davis
29st. 28pearl river
29st. 29cape girardeau
29ste. 29new madrid
30big 29st. charles
30deer 29st. clair
30golden 29st. francois
30judith 29st. louis
30lewis 29st. louis
30powder 29ste. genevieve
30silver 30big horn
30sweet 30deer lodge
31box 30golden valley
31keya 30judith basin
31red 30lewis and clark
31scotts 30powder river
32carson 30silver bow
32white 30sweet grass
34cape 31box butte
35de 31keya paha
35do??a 31red willow
35los 31scotts bluff
35rio 32carson city
35san 32white pine
35san 34cape may
35santa 35de baca
36new 35dona ana
36st. 35los alamos
37new 35rio arriba
38golden 35san juan
38grand 35san miguel
39van 35santa fe
40la 36new york
40le 36st. lawrence
40roger 37new hanover
40santa 38golden valley
41hood 38grand forks
46bon 39van wert
46charles 40la paz
46fall 40le flore
46oglala 40roger mills
47van 40santa cruz
48deaf 41hood river
48el 46bon homme
48fort 46charles mix
48jeff 46fall river
48jim 46oglala lakota
48jim 47van buren
48la 48deaf smith
48live 48el paso
48palo 48fort bend
48red 48jeff davis
48san 48jim hogg
48san 48jim wells
48san 48la salle
48san 48live oak
48tom 48palo pinto
48val 48red river
48van 48san augustine
49box 48san jacinto
49salt 48san patricio
49san 48san saba
50grand 48tom green
50hot 48val verde
50little 48van zandt
51buena 49box elder
51charles 49salt lake
51colonial 49san juan
51falls 50grand isle
51isle 50hot spring
51james 50little river
51king 51buena vista
51king 51charles city
51king 51colonial heights
51new 51falls church
51newport 51isle of wight
51prince 51james city
51prince 51king and queen
51prince 51king george
51st. 51king william
51van 51manassas park
51virginia 51new kent
53grays 51newport news
53pend 51prince edward
53san 51prince george
53walla 51prince william
55eau 51st. francis
55fond 51van buren
55la 51virginia beach
55st. 53grays harbor
56big 53pend oreille
56hot 53san juan
60contra 53walla walla
60del 55eau claire
60el 55fond du lac
60los 55green lake
60san 55la crosse
60san 55st. croix
60san 56big horn
60san 56hot springs
60san 60contra costa
60san 60del norte
60san 60el dorado
60santa 60los angeles
60santa 60san benito
60santa 60san bernardino
80clear 60san diego
80el 60san francisco
80kit 60san joaquin
80la 60san luis obispo
80las 60san mateo
81rio 60santa barbara
81rio 60santa clara
81san 60santa cruz
81san 80clear creek
90new 80el paso
90new 80kit carson

## Match the names using SBERT

In [126]:
%pip install transformers faiss-cpu

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: transformers in /Users/kevinle/Library/Python/3.9/lib/python/site-packages (4.46.2)
Requirement already satisfied: faiss-cpu in /Users/kevinle/Library/Python/3.9/lib/python/site-packages (1.9.0)
Requirement already satisfied: filelock in /Users/kevinle/Library/Python/3.9/lib/python/site-packages (from transformers) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /Users/kevinle/Library/Python/3.9/lib/python/site-packages (from transformers) (0.26.2)
Requirement already satisfied: numpy>=1.17 in /Users/kevinle/Library/Python/3.9/lib/python/site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /Users/kevinle/Library/Python/3.9/lib/python/site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /Users/kevinle/Library/Python/3.9/lib/python/site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /Users/kevinle/Library/Python/3.9/lib/python/site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /Users/kevinle/Library/Python/3.9/lib/python/site-packages (from transformers) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /Users/kevinle/Library/Python/3.9/lib/python/site-packages (from transformers) (0.4.5)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /Users/kevinle/Library/Python/3.9/lib/python/site-packages (from transformers) (0.20.3)
Requirement already satisfied: tqdm>=4.27 in /Users/kevinle/Library/Python/3.9/lib/python/site-packages (from transformers) (4.67.0)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/kevinle/Library/Python/3.9/lib/python/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (2024.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /Users/kevinle/Library/Python/3.9/lib/python/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/kevinle/Library/Python/3.9/lib/python/site-packages (from requests->transformers) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/kevinle/Library/Python/3.9/lib/python/site-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/kevinle/Library/Python/3.9/lib/python/site-packages (from requests->transformers) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /Users/kevinle/Library/Python/3.9/lib/python/site-packages (from requests->transformers) (2024.8.30)
Note: you may need to restart the kernel to use updated packages.

In [127]:
# import pandas as pd
# from sentence_transformers import SentenceTransformer, util

# w, i = wiki["fips_county"], immi["fips_county"] # Find match of w in i 

# # Load SBERT Model
# model = SentenceTransformer('all-MiniLM-L6-v2')

# # Function to compute the longest prefix match length
# def prefix_match_length(query, candidate):
#     match_len = 0
#     for q_char, c_char in zip(query, candidate):
#         if q_char == c_char:
#             match_len += 1
#         else:
#             break
#     return match_len

# # Compute prefix match lengths for all query-candidate pairs
# results = []
# for query in w:
#     for candidate in i:
#         prefix_len = prefix_match_length(query, candidate)
#         results.append((query, candidate, prefix_len))

# # Convert results to DataFrame
# results_df = pd.DataFrame(results, columns=["Query", "Candidate", "Prefix Match Length"])

# # Filter to retain only candidates with the longest prefix matches for each query
# max_prefix_df = results_df.loc[results_df.groupby("Query")["Prefix Match Length"].idxmax()]

# # Compute embeddings and semantic similarity for remaining pairs
# max_prefix_df["Query Embedding"] = max_prefix_df["Query"].apply(lambda x: model.encode(x, convert_to_tensor=True))
# max_prefix_df["Candidate Embedding"] = max_prefix_df["Candidate"].apply(lambda x: model.encode(x, convert_to_tensor=True))
# max_prefix_df["Cosine Similarity"] = max_prefix_df.apply(
#     lambda row: util.pytorch_cos_sim(row["Query Embedding"], row["Candidate Embedding"]).item(), axis=1
# )

# # Select the best match for each query based on cosine similarity
# final_results = []
# for query in w:
#     subset = max_prefix_df[max_prefix_df["Query"] == query]
#     best_match = subset.loc[subset["Cosine Similarity"].idxmax()]
#     final_results.append((query, best_match["Candidate"], best_match["Cosine Similarity"]))

# # Convert final results to DataFrame
# final_results_df = pd.DataFrame(final_results, columns=["Query", "Best Match", "Similarity Score"])

# # Save results
# final_results_df.to_csv("w_to_i_sbert_matches.csv", index=False)

# # Display results
# print(final_results_df)

## FAISS for scalability

In [128]:
import faiss
import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer

w, i = wiki["fips_county"], immi["fips_county"] # Find match of w in i 

# Load SBERT model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Function to compute prefix match length
def prefix_match_length(query, candidate):
    match_len = 0
    for q_char, c_char in zip(query, candidate):
        if q_char == c_char:
            match_len += 1
        else:
            break
    return match_len

# Step 1: Prefix Matching
results = []
for query in w:
    prefix_scores = [(candidate, prefix_match_length(query, candidate)) for candidate in i]
    max_prefix_length = max(score for _, score in prefix_scores)
    filtered_candidates = [candidate for candidate, score in prefix_scores if score == max_prefix_length]
    results.append((query, filtered_candidates))

# Step 2: Semantic Search with FAISS
final_results = []
for query, filtered_candidates in results:
    if not filtered_candidates:
        final_results.append((query, None, 0))  # No match
        continue

    # Compute embeddings for filtered candidates and the query
    query_embedding = model.encode([query], convert_to_tensor=False)
    candidate_embeddings = model.encode(filtered_candidates, convert_to_tensor=False)

    # Normalize embeddings for cosine similarity
    query_embedding = np.array(query_embedding / np.linalg.norm(query_embedding, axis=1, keepdims=True))
    candidate_embeddings = np.array(candidate_embeddings / np.linalg.norm(candidate_embeddings, axis=1, keepdims=True))

    # Build FAISS index for filtered candidates
    dimension = query_embedding.shape[1]  # Embedding size (e.g., 384 for SBERT)
    index = faiss.IndexFlatIP(dimension)  # Index for Inner Product (cosine similarity after normalization)
    index.add(candidate_embeddings)

    # Perform ANN search
    _, indices = index.search(query_embedding, 1)  # Top 1 match

    # Map results back to candidate names
    best_match_idx = indices[0][0]
    best_match = filtered_candidates[best_match_idx]
    final_results.append((query, best_match))

# Convert results to DataFrame
final_results_df = pd.DataFrame(final_results, columns=["Query", "Best Match"])

# Save results to a CSV
final_results_df.to_csv("faiss_matches.csv", index=False)

# Display results
print(final_results_df)

KeyboardInterrupt:

## Merge

In [ ]:
best_match = pd.read_csv("faiss_matches.csv")

# Map `fips_county` in wiki to `Best Match` in faiss_matches
wiki = wiki.merge(best_match, left_on='fips_county', right_on='Query', how='left')

# Drop unnecessary columns for clarity (optional)
wiki = wiki.drop(columns=['Query'])

# Rename `Best Match` column to `mapped_match` for clarity
wiki = wiki.rename(columns={'Best Match': 'mapped_match'})
# Duplicate the `fips_county` column and rename it to `mapped_match`
immi['mapped_match'] = immi['fips_county']

In [ ]:
merged_data = pd.merge(immi, wiki, on='mapped_match', how='inner').drop_duplicates("fips_county_y").sort_values("name")
print("Shape of merged dataset is:", merged_data.shape)

merged_data

Shape of merged dataset is: (3064, 69)

,stname,name,fips,"Net Migration Rate 2010s, total, ages 00-04","Net Migration Rate 2010s, total, ages 05-09","Net Migration Rate 2010s, total, ages 10-14","Net Migration Rate 2010s, total, ages 15-19","Net Migration Rate 2010s, total, ages 20-24","Net Migration Rate 2010s, total, ages 25-29","Net Migration Rate 2010s, total, ages 30-34",...,Population (2010),Land Area km²,Land Area mi²,Water Area km²,Water Area mi²,Total Area km²,Total Area mi²,Latitude,Longitude,fips_county_y
2206,South Carolina,abbeville,45001,-1.34,-1.19,-4.58,3.01,-2.78,-27.26,-20.06,...,25417,1270.348,490.484,53.116,20.508,1323.464,510.992,+34.213809°,–82.460460°,45abbeville
879,Louisiana,acadia,22001,-10.85,-8.98,-11.27,-14.32,-26.20,-18.43,-4.28,...,61773,1696.751,655.119,6.049,2.335,1702.799,657.454,+30.291497°,–92.411037°,22acadia
2778,Virginia,accomack,51001,-0.65,-7.37,-0.13,-6.86,-15.57,-8.94,4.90,...,33164,1164.189,449.496,2228.794,860.542,3392.983,1310.038,+37.765944°,–75.757807°,51accomack
302,Idaho,ada,16001,6.15,20.24,19.00,14.00,5.78,31.77,38.96,...,392365,2726.158,1052.576,20.425,7.886,2746.583,1060.462,+43.447861°,–116.244456°,16ada
1347,Missouri,adair,29001,-7.09,-9.33,-14.97,109.99,281.10,-46.93,-74.65,...,25607,1469.361,567.324,5.469,2.112,1474.830,569.436,+40.190666°,–92.603592°,29adair
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3305,Colorado,yuma,8125,3.14,7.81,-1.37,-10.00,-22.47,-16.56,21.56,...,10043,6123.780,2364.405,11.135,4.299,6134.915,2368.704,+40.000631°,–102.422649°,81yuma
2102,Arizona,yuma,4027,-5.29,-8.58,-10.35,-2.15,4.37,-6.75,-9.08,...,195751,14281.174,5513.992,13.254,5.117,14294.428,5519.109,+32.773942°,–113.910905°,40yuma
2677,Texas,zapata,48505,-4.06,-11.08,-11.41,-9.74,-17.01,-28.73,-26.90,...,14018,2585.876,998.412,154.371,59.603,2740.247,1058.015,+26.996981°,–99.182603°,48zapata
2678,Texas,zavala,48507,-17.89,-19.47,-24.64,-18.70,-22.71,-34.40,-35.64,...,11677,3360.267,1297.406,11.210,4.328,3371.477,1301.734,+28.864652°,–99.759830°,48zavala
2315,South Dakota,ziebach,46137,-2.89,-25.15,-37.97,-18.57,-19.50,-27.99,-46.50,...,2801,5079.670,1961.272,24.212,9.348,5103.883,1970.620,+44.981666°,–101.669225°,46ziebach

In [ ]:
data["statecounty_x"], merged_data["name"]

(2317    abbeville
 1114       acadia
 2821     accomack
 552           ada
 790         adair
           ...
 111          yuma
 308          yuma
 2776       zapata
 2777       zavala
 2428      ziebach
 Name: statecounty_x, Length: 3143, dtype: object,
 2206    abbeville
 879        acadia
 2778     accomack
 302           ada
 1347        adair
           ...
 3305         yuma
 2102         yuma
 2677       zapata
 2678       zavala
 2315      ziebach
 Name: name, Length: 3064, dtype: object)

In [ ]:
data["statecounty_x"].shape, merged_data['name'].shape

s1, s2 = data["statecounty_x"], merged_data["name"]
# Align the Series
common_elements = set(s1).intersection(s2)

# Count the number of common elements
common_elements_count = len(common_elements)

print(f'Number of common elements: {common_elements_count}')

Number of common elements: 1700

In [ ]:
# Merge everything here

merged = pd.merge(data, merged_data, left_on="statecounty_x", right_on="name",  how="left")

In [ ]:
merged

,statecounty_x,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2016,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2017,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2018,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2019,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2020,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2021,Percent_Of_Days_With_Level_Of_PM2.5_Exceeding_The_Standard_EPA2016,Percent_Of_Days_With_Level_Of_PM2.5_Exceeding_The_Standard_EPA2017,Percent_Of_Days_With_Level_Of_PM2.5_Exceeding_The_Standard_EPA2018,...,Population (2010),Land Area km²,Land Area mi²,Water Area km²,Water Area mi²,Total Area km²,Total Area mi²,Latitude,Longitude,fips_county_y
0,abbeville,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25417.0,1270.348,490.484,53.116,20.508,1323.464,510.992,+34.213809°,–82.460460°,45abbeville
1,acadia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,61773.0,1696.751,655.119,6.049,2.335,1702.799,657.454,+30.291497°,–92.411037°,22acadia
2,accomack,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33164.0,1164.189,449.496,2228.794,860.542,3392.983,1310.038,+37.765944°,–75.757807°,51accomack
3,ada,6.3,9.2,7.9,5.3,7.7,9.3,0.0%,5.0%,0.8%,...,392365.0,2726.158,1052.576,20.425,7.886,2746.583,1060.462,+43.447861°,–116.244456°,16ada
4,adair,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25607.0,1469.361,567.324,5.469,2.112,1474.830,569.436,+40.190666°,–92.603592°,29adair
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16133,yuma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10043.0,6123.780,2364.405,11.135,4.299,6134.915,2368.704,+40.000631°,–102.422649°,81yuma
16134,yuma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,195751.0,14281.174,5513.992,13.254,5.117,14294.428,5519.109,+32.773942°,–113.910905°,40yuma
16135,zapata,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14018.0,2585.876,998.412,154.371,59.603,2740.247,1058.015,+26.996981°,–99.182603°,48zapata
16136,zavala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11677.0,3360.267,1297.406,11.210,4.328,3371.477,1301.734,+28.864652°,–99.759830°,48zavala
16137,ziebach,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2801.0,5079.670,1961.272,24.212,9.348,5103.883,1970.620,+44.981666°,–101.669225°,46ziebach

In [ ]:
merged.to_csv("three_data_merged.csv")

In [ ]:
import pandas as pd

merged = pd.read_csv("../three_data_merged.csv")

/var/folders/5b/z7m8dzcs5td_8q7jrcf_9spm0000gn/T/ipykernel_1299/1468319545.py:3: DtypeWarning: Columns (250,251,256,257,258,259,260,265,266,267,268,287,288,294,297,298,317,318,319,327,328,339,340,347,348,349,350,355,356,357,358,370,373,375,378,386,387,388,389,390,391,392,394,395) have mixed types. Specify dtype option on import or set low_memory=False.
  merged = pd.read_csv("../three_data_merged.csv")

In [ ]:
merged

,statecounty_x,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2016,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2017,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2018,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2019,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2020,Highest_PM2.5_Concentration_microgram/m^3_of_Annual_Average_EPA2021,Percent_Of_Days_With_Level_Of_PM2.5_Exceeding_The_Standard_EPA2016,Percent_Of_Days_With_Level_Of_PM2.5_Exceeding_The_Standard_EPA2017,Percent_Of_Days_With_Level_Of_PM2.5_Exceeding_The_Standard_EPA2018,...,Population (2010),Land Area km²,Land Area mi²,Water Area km²,Water Area mi²,Total Area km²,Total Area mi²,Latitude,Longitude,fips_county_y
0,abbeville,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25417.0,1270.348,490.484,53.116,20.508,1323.464,510.992,+34.213809°,–82.460460°,45abbeville
1,acadia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,61773.0,1696.751,655.119,6.049,2.335,1702.799,657.454,+30.291497°,–92.411037°,22acadia
2,accomack,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33164.0,1164.189,449.496,2228.794,860.542,3392.983,1310.038,+37.765944°,–75.757807°,51accomack
3,ada,6.3,9.2,7.9,5.3,7.7,9.3,0.0%,5.0%,0.8%,...,392365.0,2726.158,1052.576,20.425,7.886,2746.583,1060.462,+43.447861°,–116.244456°,16ada
4,adair,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7682.0,1474.404,569.271,2.598,1.003,1477.002,570.274,+41.328528°,–94.478164°,19adair
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16133,yuma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,195751.0,14281.174,5513.992,13.254,5.117,14294.428,5519.109,+32.773942°,–113.910905°,40yuma
16134,yuma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10043.0,6123.780,2364.405,11.135,4.299,6134.915,2368.704,+40.000631°,–102.422649°,81yuma
16135,zapata,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14018.0,2585.876,998.412,154.371,59.603,2740.247,1058.015,+26.996981°,–99.182603°,48zapata
16136,zavala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11677.0,3360.267,1297.406,11.210,4.328,3371.477,1301.734,+28.864652°,–99.759830°,48zavala
16137,ziebach,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2801.0,5079.670,1961.272,24.212,9.348,5103.883,1970.620,+44.981666°,–101.669225°,46ziebach